# Generated by Django 5.1.4 on 2025-01-03 14:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e110c2f6-3dad-4c9d-aa9a-4010729a553f'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
