# Generated by Django 5.0.3 on 2024-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_image_remove_profile_job_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, height_field=300, upload_to='profile-image/', width_field=300),
        ),
    ]
